<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit2f9c6f67feda1fec3a11fcfb052a090c
{
    public static $prefixesPsr0 = array (
        'P' => 
        array (
            'Phpml' => 
            array (
                0 => __DIR__ . '/..' . '/php-ai/php-ml/src',
            ),
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixesPsr0 = ComposerStaticInit2f9c6f67feda1fec3a11fcfb052a090c::$prefixesPsr0;
            $loader->classMap = ComposerStaticInit2f9c6f67feda1fec3a11fcfb052a090c::$classMap;

        }, null, ClassLoader::class);
    }
}
