<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit5f34ec3cff232cc76ab3c39641c88a65
{
    public static $prefixesPsr0 = array (
        'N' => 
        array (
            'NlpTools\\' => 
            array (
                0 => __DIR__ . '/..' . '/nlp-tools/nlp-tools/src',
            ),
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixesPsr0 = ComposerStaticInit5f34ec3cff232cc76ab3c39641c88a65::$prefixesPsr0;
            $loader->classMap = ComposerStaticInit5f34ec3cff232cc76ab3c39641c88a65::$classMap;

        }, null, ClassLoader::class);
    }
}
